//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.DataAccess.Mapping
{
    #pragma warning disable 1573
    using Logistika.Service.Common.Entities.ErrorLog;
    using System.Data.Entity.ModelConfiguration;

    internal partial class SystemErrorLogMapping : EntityTypeConfiguration<SystemErrorLog>
    {
        public SystemErrorLogMapping()
        {					
    		this.HasKey(t => t.SystemErrorLog_PK);		
    		this.ToTable("SYSTEM_ERROR_LOG");
    		this.Property(t => t.SystemErrorLog_PK).HasColumnName("SystemErrorLog_PK");
    		this.Property(t => t.Number).HasColumnName("Number");
    		this.Property(t => t.Severity).HasColumnName("Severity").IsUnicode(false);
    		this.Property(t => t.State).HasColumnName("State").IsUnicode(false);
    		this.Property(t => t.ProcedureID).HasColumnName("ProcedureID").IsUnicode(false);
    		this.Property(t => t.Line).HasColumnName("Line").IsUnicode(false);
    		this.Property(t => t.Message).HasColumnName("Message").IsUnicode(false);
    		this.Property(t => t.AdditionalInfo).HasColumnName("AdditionalInfo").IsUnicode(false);
            this.Property(t => t.LastModifiedDt).HasColumnName("LastModifiedDt");
            this.Property(t => t.LastModifiedBy).HasColumnName("LastModifiedBy").IsRequired().IsUnicode(false).HasMaxLength(255);
    		
    	}
    }
}
