//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.DataAccess.Mapping
{
    #pragma warning disable 1573
    using Logistika.Service.Common.Entities.ErrorLog;
    using System.Data.Entity.ModelConfiguration;
    
    internal partial class WebServiceLogMapping : EntityTypeConfiguration<WebServiceLog>
    {
        public WebServiceLogMapping()
        {					
    		this.HasKey(t => t.WSLog_PK);		
    		this.ToTable("WEB_SERVICE_LOG");
    		this.Property(t => t.WSLog_PK).HasColumnName("WSLog_PK");
    		this.Property(t => t.WSResponseID).HasColumnName("WSResponseID").IsRequired().IsUnicode(false).HasMaxLength(50);
    		this.Property(t => t.WSServiceName).HasColumnName("WSServiceName").IsRequired().IsUnicode(false).HasMaxLength(255);
    		this.Property(t => t.WSConsumer_FK).HasColumnName("WSConsumer_FK");
    		this.Property(t => t.WSUserId).HasColumnName("WSUserId").IsUnicode(false).HasMaxLength(255);
    		this.Property(t => t.IPAddress).HasColumnName("IPAddress").IsUnicode(false).HasMaxLength(255);
    		this.Property(t => t.DeviceType).HasColumnName("DeviceType").IsUnicode(false).HasMaxLength(255);
    		this.Property(t => t.ResponseTime).HasColumnName("ResponseTime").IsUnicode(false).HasMaxLength(255);
    		this.Property(t => t.ResponseStatus).HasColumnName("ResponseStatus").IsUnicode(false).HasMaxLength(50);
    		this.Property(t => t.RequestDetail).HasColumnName("RequestDetail").IsUnicode(false);
    		this.Property(t => t.ResponseDetail).HasColumnName("ResponseDetail").IsUnicode(false);
            this.Property(t => t.LastModifiedBy).HasColumnName("LastModifiedBy").IsRequired().IsUnicode(false).HasMaxLength(255);
            this.Property(t => t.LastModifiedDt).HasColumnName("LastModifiedDt");
    	}
    }
}
