//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System;

    public partial class AocResponseQueue
    {
        public long AOCResponseQueue_PK { get; set; }
        public string AOCResponseExternalID { get; set; }
        public string AOCResponseExternalLineItemID { get; set; }
        public string JobNumber { get; set; }
        public string ShipmentID { get; set; }
        public string KnipperOrderID { get; set; }
        public string OrderSouceOrderID { get; set; }
        public string OrderFormSequenceNumber { get; set; }
        public string ElectronicSignatureString { get; set; }
        public string SignatureImagePath { get; set; }
        public string SignedByName { get; set; }
        public string SignedByTitle { get; set; }
        public string SignedDt { get; set; }
        public string ProductNDC { get; set; }
        public string ProductDescription { get; set; }
        public string ShippedQuantity { get; set; }
        public string ReceivedQuantity { get; set; }
        public string LotNumber { get; set; }
        public Nullable<System.DateTime> CreateDt { get; set; }
        public Nullable<System.DateTime> ProcessDt { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorCode { get; set; }
        public string ExportedDt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
        public string SysUser { get; set; }
        public Nullable<System.DateTime> SysDt { get; set; }
        public string AuditAction { get; set; }
    }
}
