//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System;

    public partial class AocResponseMobileQueue
    {
        public int AOCResponseMobileQueue_PK { get; set; }
        public string PickSlip { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public string PractitionerComments { get; set; }
        public bool IsDiscrepancy { get; set; }
        public string SignaturePath { get; set; }
        public Nullable<System.DateTime> ProcessedDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDt { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDt { get; set; }
        public string AuditAction { get; set; }
        public string SigneeFirstName { get; set; }
        public string SigneeLastName { get; set; }
        public string SigneeProfTitle { get; set; }
        public string SignatureImage { get; set; }
    }
}
