//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System.Collections.Generic;
    
    public partial class AocResponseStatusReasonType
    {
        public AocResponseStatusReasonType()
        {
            this.AocResponseStatusReason = new HashSet<AocResponseStatusReason>();
        }
    
        public int AOCResponseStatusReasonType_PK { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDt { get; set; }
    
        public virtual ICollection<AocResponseStatusReason> AocResponseStatusReason { get; set; }
    }
}
