//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System.Collections.Generic;
    
    public partial class AocResponseModificationType
    {
        public AocResponseModificationType()
        {
            this.AocResponseModification = new HashSet<AocResponseModification>();
        }
    
        public int AOCResponseModificationType_PK { get; set; }
        public int Sequence { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDt { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDt { get; set; }
        public string AuditAction { get; set; }
    
        public virtual ICollection<AocResponseModification> AocResponseModification { get; set; }
    }
}
