//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System;

    public partial class Client
    {
        public int Client_PK { get; set; }
        public string BillingID { get; set; }
        public string Name { get; set; }
        public string PMSID { get; set; }
        public string OMSID { get; set; }
        public string WMSID { get; set; }
        public string TMSID { get; set; }
        public int Status_FK { get; set; }
        public string Website { get; set; }
        public string AccessURL { get; set; }
        public string LeftImagePath { get; set; }
        public string RightImagePath { get; set; }
        public string DataEntryImageFileDropPath { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> StatusDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDt { get; set; }
        public string Sysuser { get; set; }
        public System.DateTime SysDt { get; set; }
        public string AuditAction { get; set; }
    }
}
