//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System;

    public partial class OFFER
    {
        public string Order_Id { get; set; }
        public string Shipment_id { get; set; }
        public string Offers_Id { get; set; }
        public Nullable<int> Offord_Quantity { get; set; }
        public string item { get; set; }
    }
}
