//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class QnaAnswer
    {
        public QnaAnswer()
        {
            this.AocResponseQna = new HashSet<AocResponseQna>();
        }
    
        public int QNAAnswer_PK { get; set; }
        public int QNAQuestion_FK { get; set; }
        public string Code { get; set; }
        public string Answer { get; set; }
        public string Description { get; set; }
        public int Sequence { get; set; }
        public Nullable<int> AssociatedQNAQuestion_FK { get; set; }
        public bool IsTextField { get; set; }
        public bool IsDefault { get; set; }
        public string AnswerTextDefault { get; set; }
        public string ImportFieldCode { get; set; }
        public bool IsDateFormat { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDt { get; set; }
        public string Sysuser { get; set; }
        public System.DateTime SysDt { get; set; }
        public string AuditAction { get; set; }
    
        public virtual ICollection<AocResponseQna> AocResponseQna { get; set; }
    }
}
