//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System;

    public partial class SYSTEM_ERROR_LOG
    {
        public int SystemErrorLog_PK { get; set; }
        public Nullable<int> Number { get; set; }
        public string Severity { get; set; }
        public string State { get; set; }
        public string ProcedureID { get; set; }
        public string Line { get; set; }
        public string Message { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string Sysuser { get; set; }
        public System.DateTime SysDt { get; set; }
        public string AuditAction { get; set; }
    }
}
