//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System;

    public partial class WMS_SHIPPING_CONTAINER_TAB
    {
        public decimal INTERNAL_CONTAINER_NUM { get; set; }
        public string CONTAINER_ID { get; set; }
        public string warehouse { get; set; }
        public string CONTAINER_TYPE { get; set; }
        public string CONTAINER_CLASS { get; set; }
        public decimal status { get; set; }
        public string STATUS_FAILED { get; set; }
        public Nullable<decimal> PARENT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string WEIGHT_UM { get; set; }
        public Nullable<decimal> VOLUME { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public string DIMENSION_UM { get; set; }
        public string VOLUME_UM { get; set; }
        public Nullable<decimal> VALUE { get; set; }
        public Nullable<decimal> INTERNAL_SHIPMENT_NUM { get; set; }
        public Nullable<decimal> INTERNAL_SHIPMENT_LINE_NUM { get; set; }
        public string COMPANY { get; set; }
        public string ITEM { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string QUANTITY_UM { get; set; }
        public string NMFC_CODE { get; set; }
        public string STATUS_FLOW_NAME { get; set; }
        public string HAZARDOUS_CODE { get; set; }
        public string MANIFEST_STATE { get; set; }
        public string MANIFEST_CARR_SERVICE_SYMBOL { get; set; }
        public Nullable<System.DateTime> MANIFEST_DATE_TIME { get; set; }
        public string TRACKING_NUMBER { get; set; }
        public Nullable<decimal> TOTAL_FREIGHT_CHARGE { get; set; }
        public Nullable<decimal> BASE_FREIGHT_CHARGE { get; set; }
        public Nullable<decimal> FREIGHT_DISCOUNT { get; set; }
        public Nullable<decimal> ACCESSORIAL_CHARGE { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public Nullable<decimal> USER_DEF7 { get; set; }
        public Nullable<decimal> USER_DEF8 { get; set; }
        public string USER_STAMP { get; set; }
        public string PROCESS_STAMP { get; set; }
        public System.DateTime DATE_TIME_STAMP { get; set; }
        public Nullable<decimal> INTERNAL_ORDER_NUM { get; set; }
        public Nullable<System.DateTime> MANIFEST_FOR_DATE { get; set; }
        public Nullable<decimal> TREE_UNIT { get; set; }
        public Nullable<System.DateTime> PLANNED_DELIVERY_DATE_TIME { get; set; }
        public Nullable<decimal> BUNDLE_ID { get; set; }
        public Nullable<decimal> MSN { get; set; }
        public string LOCATION { get; set; }
        public Nullable<decimal> GROUP_POSITION { get; set; }
        public Nullable<decimal> LAUNCH_NUM { get; set; }
        public Nullable<decimal> CONTAINER_COUNT_NUMBER { get; set; }
        public Nullable<decimal> CONTAINER_COUNT_TOTAL { get; set; }
        public Nullable<decimal> GROUP_NUM { get; set; }
        public string WORK_ZONE { get; set; }
        public string INTERFACE_RECORD_ID { get; set; }
        public string PARENT_CONTAINER_ID { get; set; }
        public Nullable<decimal> INTERNAL_SHIP_ALLOC_NUM { get; set; }
        public string WORK_CREATED { get; set; }
        public string HUNDREDWEIGHT { get; set; }
        public string MANIFEST_ID { get; set; }
        public Nullable<System.DateTime> MANIFEST_CLOSE_DATE_TIME { get; set; }
        public string EPC { get; set; }
        public string LOT { get; set; }
        public string URI { get; set; }
        public Nullable<decimal> RETURNS_TOTAL_FREIGHT_CHARGE { get; set; }
        public Nullable<decimal> RETURNS_BASE_FREIGHT_CHARGE { get; set; }
        public Nullable<decimal> RETURNS_FREIGHT_DISCOUNT { get; set; }
        public Nullable<decimal> RETURNS_ACCESSORIAL_CHARGE { get; set; }
        public Nullable<decimal> RETURNS_CALLTAG_FEE { get; set; }
        public string RETURNS_TRACKING_NUMBER { get; set; }
        public Nullable<decimal> RETURNS_MSN { get; set; }
        public string RETURNS_PRINT_LABEL { get; set; }
        public Nullable<decimal> WORLD_EASE_ID { get; set; }
        public Nullable<decimal> WORLD_EASE_GROUP_STATUS { get; set; }
        public string LOGISTICS_UNIT { get; set; }
        public string PARENT_LOGISTICS_UNIT { get; set; }
        public Nullable<decimal> PALLET_SEQUENCE { get; set; }
        public string ORIGINAL_PICK_LOC { get; set; }
    }
}
