//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System;

    public partial class WMS_COMPANY_TAB
    {
        public string COMPANY { get; set; }
        public string NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string POSTAL_CODE { get; set; }
        public string RETURNS_NAME { get; set; }
        public string RETURNS_ADDRESS1 { get; set; }
        public string RETURNS_ADDRESS2 { get; set; }
        public string RETURNS_ADDRESS3 { get; set; }
        public string RETURNS_CITY { get; set; }
        public string RETURNS_STATE { get; set; }
        public string RETURNS_COUNTRY { get; set; }
        public string RETURNS_POSTAL_CODE { get; set; }
        public string COMPANY_PREFIX { get; set; }
        public string PHONE_NUM { get; set; }
        public string FAX_NUM { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string HOST_INTERFACE_SOURCE { get; set; }
        public string IP_ADDRESS { get; set; }
        public string ACTIVE { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public Nullable<decimal> USER_DEF7 { get; set; }
        public Nullable<decimal> USER_DEF8 { get; set; }
        public string USER_STAMP { get; set; }
        public string PROCESS_STAMP { get; set; }
        public System.DateTime DATE_TIME_STAMP { get; set; }
        public string ATTENTION_TO { get; set; }
        public string RETURNS_ATTENTION_TO { get; set; }
        public string RETURNS_PHONE_NUM { get; set; }
        public string RETURNS_FAX_NUM { get; set; }
        public string RETURNS_EMAIL_ADDRESS { get; set; }
        public string FREIGHT_BILL_TO_NAME { get; set; }
        public string FREIGHT_BILL_TO_ADDRESS1 { get; set; }
        public string FREIGHT_BILL_TO_ADDRESS2 { get; set; }
        public string FREIGHT_BILL_TO_ADDRESS3 { get; set; }
        public string FREIGHT_BILL_TO_ATTENTION_TO { get; set; }
        public string FREIGHT_BILL_TO_CITY { get; set; }
        public string FREIGHT_BILL_TO_STATE { get; set; }
        public string FREIGHT_BILL_TO_COUNTRY { get; set; }
        public string FREIGHT_BILL_TO_POSTAL_CODE { get; set; }
        public string FREIGHT_BILL_TO_PHONE_NUM { get; set; }
        public string FREIGHT_BILL_TO_FAX_NUM { get; set; }
        public string FREIGHT_BILL_TO_EMAIL_ADDRESS { get; set; }
        public string ORDER_ID_PREFIX { get; set; }
        public string FISCAL_CALENDAR_NAME { get; set; }
        public string WEB_HEADER_URL_LEFT { get; set; }
        public string WEB_HEADER_URL_CENTER { get; set; }
        public string WEB_HEADER_URL_RIGHT { get; set; }
        public string WEB_HEADER_GRAPHIC_LEFT { get; set; }
        public string WEB_HEADER_GRAPHIC_CENTER { get; set; }
        public string WEB_HEADER_GRAPHIC_RIGHT { get; set; }
        public string RECEIPT_ID_PREFIX { get; set; }
        public string AVAILABILITY_CHECKING { get; set; }
        public string PURCHASE_ORDER_ID_PREFIX { get; set; }
    }
}
