//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System;

    public partial class WMS_DELIVERY_SHIPMENT_HDR_TAB
    {
        public string WAREHOUSE { get; set; }
        public string SHIPMENT_ID { get; set; }
        public decimal INTERNAL_SHIPMENT_NUM { get; set; }
        public string COMPANY { get; set; }
        public string CUSTOMER { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string SHIP_TO { get; set; }
        public string SHIP_TO_NAME { get; set; }
        public string SHIP_TO_CITY { get; set; }
        public string SHIP_TO_STATE { get; set; }
        public string SHIP_TO_POSTAL_CODE { get; set; }
        public string SHIP_TO_PHONE_NUM { get; set; }
        public string ORDER_TYPE { get; set; }
        public string CARRIER { get; set; }
        public string CARRIER_SERVICE { get; set; }
        public string PRO_NUM_ALPHA { get; set; }
        public string BOL_NUM_ALPHA { get; set; }
        public string SIGNATURE { get; set; }
        public decimal LEADING_STS { get; set; }
        public decimal TRAILING_STS { get; set; }
        public System.DateTime ACTUAL_SHIP_DATE_TIME { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public Nullable<decimal> USER_DEF7 { get; set; }
        public Nullable<decimal> USER_DEF8 { get; set; }
        public Nullable<System.DateTime> DATE_TIME_STAMP { get; set; }
        public decimal INTERNAL_NUM { get; set; }
    }
}
