//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System;

    public partial class WMS_DELIVERY_CONTAINER_TAB
    {
        public string warehouse { get; set; }
        public decimal INTERNAL_SHIPMENT_NUM { get; set; }
        public string CONTAINER_ID { get; set; }
        public decimal STATUS { get; set; }
        public string SIGNATURE { get; set; }
        public string CARRIER { get; set; }
        public string CARRIER_SERVICE { get; set; }
        public Nullable<System.DateTime> MANIFEST_DATE_TIME { get; set; }
        public string TRACKING_NUMBER { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public Nullable<decimal> USER_DEF7 { get; set; }
        public Nullable<decimal> USER_DEF8 { get; set; }
        public Nullable<System.DateTime> DATE_TIME_STAMP { get; set; }
        public decimal INTERNAL_ID { get; set; }
    }
}
