//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System;

    public partial class WMS_SHIPMENT_HEADER_TAB
    {
        public decimal INTERNAL_SHIPMENT_NUM { get; set; }
        public string warehouse { get; set; }
        public Nullable<decimal> SHIPPING_LOAD_NUM { get; set; }
        public string SHIPMENT_ID { get; set; }
        public string LAUNCH_STEP { get; set; }
        public decimal TRAILING_STS { get; set; }
        public Nullable<System.DateTime> TRAILING_STS_DATE { get; set; }
        public string TRAILING_STS_FAILED { get; set; }
        public string ORDER_TYPE { get; set; }
        public string CONSOLIDATED { get; set; }
        public decimal LEADING_STS { get; set; }
        public Nullable<System.DateTime> LEADING_STS_DATE { get; set; }
        public string CARRIER { get; set; }
        public string LEADING_STS_FAILED { get; set; }
        public string COMPANY { get; set; }
        public string CARRIER_SERVICE { get; set; }
        public string CARRIER_GROUP { get; set; }
        public string CARRIER_TYPE { get; set; }
        public string FREIGHT_TERMS { get; set; }
        public string LIABILITY_TERMS { get; set; }
        public string CUSTOMER { get; set; }
        public string SHIP_TO { get; set; }
        public string ROUTE { get; set; }
        public string STOP { get; set; }
        public string SHIP_TO_ADDRESS1 { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string SHIP_TO_ADDRESS2 { get; set; }
        public string SHIP_TO_ADDRESS3 { get; set; }
        public string SHIP_TO_CITY { get; set; }
        public string SHIP_TO_STATE { get; set; }
        public string SHIP_TO_COUNTRY { get; set; }
        public string SHIP_TO_POSTAL_CODE { get; set; }
        public string SHIP_TO_PHONE_NUM { get; set; }
        public string SHIP_TO_FAX_NUM { get; set; }
        public string CUSTOMER_ADDRESS1 { get; set; }
        public Nullable<decimal> LAUNCH_NUM { get; set; }
        public string WEIGHT_UM { get; set; }
        public string VOLUME_UM { get; set; }
        public string ROUTING_CODE { get; set; }
        public string SINGLE_ITEM_CARTONS { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public Nullable<decimal> USER_DEF7 { get; set; }
        public string MANUALLY_ENTERED { get; set; }
        public Nullable<decimal> USER_DEF8 { get; set; }
        public string USER_STAMP { get; set; }
        public string PROCESS_STAMP { get; set; }
        public System.DateTime DATE_TIME_STAMP { get; set; }
        public string BOL_NUM_ALPHA { get; set; }
        public string PRO_NUM_ALPHA { get; set; }
        public string CUSTOMER_ADDRESS3 { get; set; }
        public string CUSTOMER_ADDRESS2 { get; set; }
        public string CUSTOMER_ATTENTION_TO { get; set; }
        public string CUSTOMER_CITY { get; set; }
        public string CUSTOMER_STATE { get; set; }
        public string CUSTOMER_COUNTRY { get; set; }
        public string CUSTOMER_POSTAL_CODE { get; set; }
        public string CUSTOMER_PHONE_NUM { get; set; }
        public string CUSTOMER_FAX_NUM { get; set; }
        public string CUSTOMER_EMAIL_ADDRESS { get; set; }
        public string SHIP_TO_NAME { get; set; }
        public string SHIP_TO_ATTENTION_TO { get; set; }
        public string SHIP_TO_EMAIL_ADDRESS { get; set; }
        public Nullable<System.DateTime> REQUESTED_DELIVERY_DATE { get; set; }
        public string REQUESTED_DELIVERY_TYPE { get; set; }
        public System.DateTime SCHEDULED_SHIP_DATE { get; set; }
        public Nullable<System.DateTime> PLANNED_SHIP_DATE { get; set; }
        public Nullable<System.DateTime> ACTUAL_SHIP_DATE_TIME { get; set; }
        public Nullable<System.DateTime> PLANNED_DELIVERY_DATE_TIME { get; set; }
        public Nullable<System.DateTime> ACTUAL_DELIVERY_DATE_TIME { get; set; }
        public string QUANTITY_UM { get; set; }
        public Nullable<decimal> TOTAL_FREIGHT_CHARGE { get; set; }
        public Nullable<decimal> BASE_FREIGHT_CHARGE { get; set; }
        public Nullable<decimal> FREIGHT_DISCOUNT { get; set; }
        public Nullable<decimal> ACCESSORIAL_CHARGE { get; set; }
        public string CONSOLIDATION_ALLOWED { get; set; }
        public string INTERMEDIATE_CONSIGNEE { get; set; }
        public string INTERMEDIATE_NAME { get; set; }
        public string INTERMEDIATE_ADDRESS1 { get; set; }
        public string INTERMEDIATE_ADDRESS2 { get; set; }
        public string INTERMEDIATE_ADDRESS3 { get; set; }
        public string INTERMEDIATE_ATTENTION_TO { get; set; }
        public string INTERMEDIATE_CITY { get; set; }
        public string INTERMEDIATE_STATE { get; set; }
        public string INTERMEDIATE_COUNTRY { get; set; }
        public string INTERMEDIATE_POSTAL_CODE { get; set; }
        public string INTERMEDIATE_PHONE_NUM { get; set; }
        public string INTERMEDIATE_FAX_NUM { get; set; }
        public string INTERMEDIATE_EMAIL_ADDRESS { get; set; }
        public string FREIGHT_BILL_TO { get; set; }
        public string FREIGHT_BILL_TO_NAME { get; set; }
        public string FREIGHT_BILL_TO_ADDRESS1 { get; set; }
        public string FREIGHT_BILL_TO_ADDRESS2 { get; set; }
        public string FREIGHT_BILL_TO_ADDRESS3 { get; set; }
        public string FREIGHT_BILL_TO_ATTENTION_TO { get; set; }
        public string FREIGHT_BILL_TO_CITY { get; set; }
        public string FREIGHT_BILL_TO_STATE { get; set; }
        public string FREIGHT_BILL_TO_COUNTRY { get; set; }
        public string FREIGHT_BILL_TO_POSTAL_CODE { get; set; }
        public string FREIGHT_BILL_TO_PHONE_NUM { get; set; }
        public string FREIGHT_BILL_TO_FAX_NUM { get; set; }
        public string FREIGHT_BILL_TO_EMAIL_ADDRESS { get; set; }
        public string ERP_ORDER { get; set; }
        public Nullable<decimal> INTERNAL_ORDER_NUM { get; set; }
        public string EXPORT_TAX_ID { get; set; }
        public string PARTIES { get; set; }
        public string LOADING_PIER { get; set; }
        public string TRANSPORTATION_MODE { get; set; }
        public string EXPORT_PORT { get; set; }
        public string UNLOADING_PORT { get; set; }
        public string CONTAINERIZED { get; set; }
        public string FTZ { get; set; }
        public string VALIDATED_LICENSE { get; set; }
        public Nullable<System.DateTime> LICENSE_EXP_DATE { get; set; }
        public string ECCN { get; set; }
        public string AUTHORIZED_EMPL_NAME { get; set; }
        public string AUTHORIZED_EMPL_TITLE { get; set; }
        public string UPLOAD_INTERFACE_BATCH { get; set; }
        public string CUSTOMER_RESIDENTIAL_FLAG { get; set; }
        public string SHIPTO_RESIDENTIAL_FLAG { get; set; }
        public string REJECTION_NOTE { get; set; }
        public string INTERFACE_RECORD_ID { get; set; }
        public string CUSTOMER_CATEGORY1 { get; set; }
        public string CUSTOMER_CATEGORY2 { get; set; }
        public string CUSTOMER_CATEGORY3 { get; set; }
        public string CUSTOMER_CATEGORY4 { get; set; }
        public string CUSTOMER_CATEGORY5 { get; set; }
        public string CUSTOMER_CATEGORY6 { get; set; }
        public string CUSTOMER_CATEGORY7 { get; set; }
        public string CUSTOMER_CATEGORY8 { get; set; }
        public string CUSTOMER_CATEGORY9 { get; set; }
        public string CUSTOMER_CATEGORY10 { get; set; }
        public string CONSOLIDATION_DOCK_LOC_AREA { get; set; }
        public string CONSOLIDATION_DOCK_LOC_POS { get; set; }
        public string PROCESS_TYPE { get; set; }
        public string CREATION_PROCESS_STAMP { get; set; }
        public Nullable<System.DateTime> CREATION_DATE_TIME_STAMP { get; set; }
        public string IMMEDIATE_NEEDS_NOTE { get; set; }
        public string ALLOCATE_COMPLETE { get; set; }
        public string ALTERNATE_EMAIL_ADDRESS { get; set; }
        public Nullable<decimal> STOP_SEQUENCE { get; set; }
        public Nullable<decimal> INTERNAL_CARRIER_NUM { get; set; }
        public string STORE_DISTRIBUTION { get; set; }
        public Nullable<decimal> TOTAL_LBR_ESTIMATE { get; set; }
        public Nullable<decimal> WEIGHT_ENTERED { get; set; }
        public Nullable<decimal> VOLUME_ENTERED { get; set; }
        public Nullable<decimal> VALUE_ENTERED { get; set; }
        public string LOCKED { get; set; }
        public string SHIPPER_CODE { get; set; }
    }
}
