//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.AOC
{
    #pragma warning disable 1573
    using System;

    public partial class WMS_ITEM_TAB
    {
        public decimal INTERNAL_ITEM_NUM { get; set; }
        public string LOCATING_RULE { get; set; }
        public string ALLOCATION_RULE { get; set; }
        public string ITEM { get; set; }
        public string COMPANY { get; set; }
        public string DESCRIPTION { get; set; }
        public string ITEM_TEMPLATE { get; set; }
        public string TEMPLATE_FIELD1 { get; set; }
        public string TEMPLATE_FIELD2 { get; set; }
        public string TEMPLATE_FIELD3 { get; set; }
        public string TEMPLATE_FIELD4 { get; set; }
        public string TEMPLATE_FIELD5 { get; set; }
        public string DIVISION { get; set; }
        public string DEPARTMENT { get; set; }
        public Nullable<decimal> COST { get; set; }
        public string ITEM_SIZE { get; set; }
        public string ITEM_COLOR { get; set; }
        public string ITEM_STYLE { get; set; }
        public string NMFC_CODE { get; set; }
        public string LOT_CONTROLLED { get; set; }
        public string CATCH_WEIGHT_REQD { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public Nullable<decimal> USER_DEF7 { get; set; }
        public Nullable<decimal> USER_DEF8 { get; set; }
        public string USER_STAMP { get; set; }
        public string PROCESS_STAMP { get; set; }
        public System.DateTime DATE_TIME_STAMP { get; set; }
        public Nullable<decimal> LIST_PRICE { get; set; }
        public Nullable<decimal> NET_PRICE { get; set; }
        public string STORAGE_TEMPLATE { get; set; }
        public string INVENTORY_TRACKING { get; set; }
        public string ITEM_CLASS { get; set; }
        public string HARMONIZED_CODE { get; set; }
        public string PREFERENCE_CRIT { get; set; }
        public string PRODUCER { get; set; }
        public string NET_COST { get; set; }
        public string COUNTRY_OF_ORIGIN { get; set; }
        public string PACKING_CLASS { get; set; }
        public string ITEM_CATEGORY1 { get; set; }
        public string ITEM_CATEGORY2 { get; set; }
        public string ITEM_CATEGORY3 { get; set; }
        public string ITEM_CATEGORY4 { get; set; }
        public string ITEM_CATEGORY5 { get; set; }
        public string ITEM_CATEGORY6 { get; set; }
        public string ITEM_CATEGORY7 { get; set; }
        public string ITEM_CATEGORY8 { get; set; }
        public string ITEM_CATEGORY9 { get; set; }
        public string ITEM_CATEGORY10 { get; set; }
        public string ALTERNATE_ITEM { get; set; }
        public string WEB_THUMBNAIL_IMG { get; set; }
        public string WEB_IMG { get; set; }
        public string AVAILABLE_ON_WEB { get; set; }
        public string IMMEDIATE_NEEDS_LOC_RULE { get; set; }
        public string IMMEDIATE_NEEDS_ELIGIBLE { get; set; }
        public string INBOUND_QC_ELIGIBLE { get; set; }
        public string INBOUND_QC_LOC_RULE { get; set; }
        public Nullable<decimal> INBOUND_QC_AMOUNT { get; set; }
        public string INBOUND_QC_AMOUNT_TYPE { get; set; }
        public string INBOUND_QC_UM { get; set; }
        public string BOM_ACTION { get; set; }
        public string LONG_DESCRIPTION { get; set; }
        public string ACTIVE { get; set; }
        public string EPC_COMPANY_PREFIX { get; set; }
        public string EPC_ITEM_REFERENCE { get; set; }
        public string SERIAL_NUM_TEMPLATE { get; set; }
        public Nullable<decimal> SERIAL_NUM_TRACKING { get; set; }
        public string FEDEX_XTN { get; set; }
        public string FEDEX_ITN { get; set; }
        public string EPC_CAGE_CODE { get; set; }
        public string LOT_TEMPLATE { get; set; }
        public Nullable<decimal> DAYS_TO_EXPIRE { get; set; }
        public string GTIN_ENABLED { get; set; }
        public string APP_IDENTIFIER { get; set; }
    }
}
