//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.ErrorLog
{
    #pragma warning disable 1573

    public partial class WebServiceLog
    {
        public int WSLog_PK { get; set; }
        public string WSResponseID { get; set; }
        public string WSServiceName { get; set; }
        public int WSConsumer_FK { get; set; }
        public string WSUserId { get; set; }
        public string IPAddress { get; set; }
        public string DeviceType { get; set; }
        public string ResponseTime { get; set; }
        public string ResponseStatus { get; set; }
        public string RequestDetail { get; set; }
        public string ResponseDetail { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDt { get; set; }
    }
}
