//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.CorsConfig
{
    #pragma warning disable 1573
    using Logistika.Service.Common.Entities.Authentication;
    using System;

    public partial class WsApiCorsConfig
    {
        public long WsApiCorsConfig_PK { get; set; }
        public Nullable<int> WSConsumer_FK { get; set; }
        public string Resources { get; set; }
        public string Origins { get; set; }
        public string Methods { get; set; }
        public Nullable<bool> AllowCookies { get; set; }
        public string RequestHeaders { get; set; }
        public string ResponseHeaders { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDt { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDt { get; set; }
        public string AuditAction { get; set; }

        public virtual WsConsumer WsConsumer { get; set; }
    }
}
