//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.Authentication
{
    #pragma warning disable 1573
    using System;

    public partial class WsCredentialApiController
    {
        public long WsCredentialApiController_PK { get; set; }
        public Nullable<int> WsCredential_FK { get; set; }
        public Nullable<long> WsApiController_FK { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDt { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDt { get; set; }
        public string AuditAction { get; set; }

        public virtual WsApiController WsApiController { get; set; }
        public virtual WsCredential WsCredential { get; set; }
    }
}
