//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistika.Service.Common.Entities.Authentication
{
    #pragma warning disable 1573
    using System.Collections.Generic;
    
    public partial class WsCredential
    {
        public WsCredential()
        {
            this.WsCredentialApiController = new HashSet<WsCredentialApiController>();
        }
    
        public int Credential_PK { get; set; }
        public int Consumer_FK { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDt { get; set; }
        public string SysUser { get; set; }
        public System.DateTime SysDt { get; set; }
        public string AuditAction { get; set; }

        public virtual WsConsumer WsConsumer { get; set; }
        public virtual ICollection<WsCredentialApiController> WsCredentialApiController { get; set; }
    }
}
